title: Sydney Trinidad
email: sydneyctrinidad@gmail.com
description:
  A website for Sydney Trinidad, hosted on GitHub Pages.
baseurl: ""
domain: sydneytrinidad.github.io
url: https://sydneytrinidad.github.io
github_username: sydneytrinidad

markdown: kramdown

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - pages
  - notes

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
      permalink: /:basename/
      author_profile: true
  - scope:
      path: "notes"
      type: "pages"
    values:
      layout: "default"
      permalink: /notes/
      author_profile: true

disqus:
    shortname: sydneytrinidad

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
