title: Sydney Trinidad
email: sydneyctrinidad@gmail.com
description:
  A website for Sydney Trinidad, hosted on GitHub Pages.
baseurl: ""
domain: sydneytrinidad.github.io
url: https://sydneytrinidad.github.io
github_username: sydneytrinidad

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
